### PR TITLE
Upgrade :fs to latest version

### PR DESCRIPTION
**Pull request by dropfen**
Not sure, why https://github.com/phoenixframework/phoenix_live_reload/commit/e54bf6fb301436797ff589e0b76a047bb79b6870 ?

But this would actually fix this issue #51

### CODE REVIEW

**Comment by chrismccord** [comment]
There are outstanding issues that we need to make sure are resolved before jumping to latest fs. Thanks!

**Comment by dropfen** [comment]
@chrismccord Please reopen, I changed the version to `1.1.0-alpha`, the used version in phoenix is 1.0 so it will not really affect it. On the other hand, AFAIK the issue with rebar3 is not totally clear, so its worth of trying. Thanks too!

**Comment by devilankur18** [comment]
@chrismccord Please reopen, fs version is still 0.9 on the master, its causing dependency conflicts with other packages. Thanks !!

**Comment by josevalim** [comment]
Folks, we cannot reopen this until the issues with rebar3 and fs are fixed. Did someone check fs issues tracker or commits to make sure the problem no longer exists? Did someone try running rebar3 and fs on windows? Simply reopening this won't automatically solve those problems.

**Comment by webdeb** [comment]
@josevalim it's not very clear, what the problems with `rebar3` actually are. Seams like `fs` maintainer is not very happy about supporting rebar3/mix etc. https://github.com/synrc/fs/pull/47 What is `mad`?

**Pull request closed without merging**
