### PR TITLE
make dirs configurable

### PR DESCRIPTION
**Pull request by m11m**

### CODE REVIEW

**Comment by m11m** [comment]
Good idea, renamed to `:watch_dirs` if that's OK.

**Comment by chrismccord** [comment]
What's the usecase here to configure the dir? It would be nice if we allowed opts to start_link so we don't need to introduce global config

**Comment by m11m** [comment]
@chrismccord  Use case is to use a different output path outside of phoenix project home directory.

It sounds like you are suggesting the configuration come down through the Application start callback?

I'm not familiar with how one would configure this in a project that depends on phoenix_live_reload, is there some resource or example you could point out regarding this?

**Comment by thehunmonkgroup** [comment]
This PR is *kind* of addressed by https://github.com/phoenixframework/phoenix_live_reload/pull/90 -- although that automatically prepends application dir to the provided paths.

Would that plus some symlink-ing get the job done?

**Comment by josevalim** [comment]
If you pass absolute paths, then the expansion in #90 won't do anything, so it should work too.

I actually should have noticed there was a previous discussion on this, sorry @chrismccord and @m11m.

**Pull request closed without merging**
